accounts/api/urls.py
from django.conf.urls import url

from django.views.generic.base  import RedirectView

from tweets.api.views import  (
    TweetListAPIView,
 )
urlpatterns = [
	url(r'^(?P<username>[\w.@+-]+)/tweet/$', TweetListAPIView.as_view(), name='list'), #/tweet/
]

accounts/urls.py
from django.conf.urls import url,include
from django.views.generic.base import RedirectView

# from .views import tweet_detail_view, tweet_list_view, TweetDetailView, TweetListView
from django.contrib.auth.views import PasswordChangeView
from .views import (
	UserDetailView,
	UserFollowView,
	edit_profile,
	#change_password

	)

urlpatterns = [
    # #url(r'^admin/', admin.site.urls),
    # url(r'^$', RedirectView.as_view(url="/")),
    # url(r'^search/$', TweetListView.as_view(), name='list'),
    # url(r'^create/$', TweetCreateView.as_view(), name='create'),
    url(r'^(?P<username>[\w.@+-]+)/$', UserDetailView.as_view(), name='detail'),
    url(r'^(?P<username>[\w.@+-]+)/follow/$', UserFollowView.as_view(), name='follow'),
	url(r'^profile/edit/$', edit_profile, name='edit_profile'),
    url(r'^profile/password/$',PasswordChangeView.as_view(template_name='accounts/change_password.html'), name='password_change')
    #url(r'^profile/password/$', change_password, name='change_password'),
    # url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'),
    # url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'),
]

tweets/urls.py
from django.conf.urls import url
from django.views.generic.base import RedirectView

# from .views import tweet_detail_view, tweet_list_view, TweetDetailView, TweetListView
from .views import (
    RetweetView,
	TweetCreateView,
	TweetDetailView,
	TweetDeleteView,
	TweetListView,
	TweetUpdateView
	)

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url="/")),
    url(r'^search/$', TweetListView.as_view(), name='list'),
    url(r'^create/$', TweetCreateView.as_view(), name='create'),
    url(r'^(?P<pk>\d+)/$', TweetDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/retweet/$', RetweetView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/update/$', TweetUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', TweetDeleteView.as_view(), name='delete'),
]

accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.urls import reverse_lazy
from django.db.models import signals
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models

# Create your models here.
class UserProfileManager(models.Manager):
	use_for_related_fields = True

	def all(self):
		qs = self.get_queryset().all()
		try:
			if self.instance:
				qs = qs.exclude(user=self.instance)
		except:
			pass
		return qs

	def toggle_follow(self, user, to_toggle_user):
		user_profile, created = UserProfile.objects.get_or_create(user=user)
		if to_toggle_user in user_profile.following.all():
			user_profile.following.remove(to_toggle_user)
			added = False
		else:
			user_profile.following.add(to_toggle_user)
			added = True
		return added

	def is_following(self, user, followed_by_user):
		user_profile, created = UserProfile.objects.get_or_create(user=user)
		if created:
			return False
		if followed_by_user in user_profile.following.all():
			return True
		return False

	def recommended(self, user, limit_to = 10):
		print(user)
		profile = user.profile
		following = profile.following.all()
		following = profile.get_following()
		qs = self.get_queryset().exclude(user__in=following).exclude(id=profile.id).order_by("?")[:5]
		return qs

class UserProfile(models.Model):
	user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='profile')
	following = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True,related_name='followed_by')

	objects  =  UserProfileManager()

	def __str__(self):
		return str(self.following.all().count())

	def get_following(self):
		users = self.following.all()
		return users.exclude(username=self.user.username)

	def get_follow_url(self):
		return reverse_lazy("profiles:follow", kwargs={"username":self.user.username})

	def get_absolute_url(self):
		return reverse_lazy("profiles:detail", kwargs={"username":self.user.username})



def post_save_user_recevier(sender, instance,  created, *args, **kwargs):
	if created:
		new_profile = UserProfile.objects.get_or_create(user=instance)
	# print(instance)


post_save.connect(post_save_user_recevier, sender=settings.AUTH_USER_MODEL)

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm

User = get_user_model()

class UserRegisterForm(forms.Form):

	username = forms.CharField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus', 'placeholder': 'Username'}), max_length=30, required=True)
	first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus', 'placeholder': 'Firstname'}), max_length=20, required=True)
	last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus', 'placeholder': 'Lastname'}), max_length=30, required=True)
	email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus' , 'placeholder': 'Email'}), required=True,)
	password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'js-password-field js-initial-focus', 'placeholder': 'Password'}), required=True,)
	# password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

	# def clean_password2(self):
	# 	password = self.cleaned_data.get('password')
	# 	password2 = self.cleaned_data.get('password2')

	# 	if password != password2:
	# 		raise forms.ValidationError("Password must match")
	# 	return password2

	def clean_username(self):
		username = self.cleaned_data.get('username')
		if User.objects.filter(username__icontains=username).exists():
			raise forms.ValidationError("This username is already taken.")
		return username

	def clean_email(self):
		email = self.cleaned_data.get('email')
		if User.objects.filter(email__icontains=email).exists():
			raise forms.ValidationError("This email is already registered.")
		return email

class EditProfileView(UserChangeForm):

	class Meta:
		model = User
	# username = forms.CharField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus', 'placeholder': 'Username'}), max_length=30, required=True)
	# first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus', 'placeholder': 'Firstname'}), max_length=20, required=True)
	# last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus', 'placeholder': 'Lastname'}), max_length=30, required=True)
	# email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'js-username-field email-input js-initial-focus' , 'placeholder': 'Email'}), required=True,)
	# password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'js-password-field js-initial-focus', 'placeholder': 'Password'}), required=True,)

		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password',
			)

accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth import get_user_model
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, PasswordChangeForm
from django.views import View
from django.views.generic import DetailView
from django.views.generic.edit import FormView
from .forms import UserRegisterForm, EditProfileView
from .models import UserProfile
from django.contrib.auth import update_session_auth_hash
# Create your views here.

User = get_user_model()

def edit_profile(request):

    if request.method == 'POST':
        form = EditProfileView(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)
            # login(request, user)
            return redirect("profiles:detail", username=username)

    else:
        form = EditProfileView(instance=request.user)

        return render(request, 'accounts/edit_profile.html', {'form': form})

def change_password(request):

    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            username = form.cleaned_data.get('username')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=username, password=raw_password)
            # login(request, user)
            return redirect("/")


    else:
        form = PasswordChangeForm(user=request.user)

        return render(request, 'accounts/change_password.html', {'form': form})


class UserRegisterView(FormView):
  template_name = 'accounts/user_register_form.html'
  form_class = UserRegisterForm
  success_url = '/login'

  def form_valid(self,form):
    #form.send_email()
    username = form.cleaned_data.get("username")
    email = form.cleaned_data.get("email")
    password = form.cleaned_data.get("password")
    first_name = form.cleaned_data.get("first_name")
    last_name = form.cleaned_data.get("last_name")

    new_user = User.objects.create(username=username, email=email, first_name=first_name, last_name=last_name)
    new_user.set_password(password)
    new_user.save()
    return super(UserRegisterView, self).form_valid(form)

class UserDetailView(DetailView):
	template_name = 'accounts/user_detail.html'
	queryset = User.objects.all()

	def get_object(self):
		return get_object_or_404(User, username__iexact=self.kwargs.get("username"))

	def get_context_data(self, *args, **kwargs):
	  	context = super(UserDetailView, self).get_context_data(*args, **kwargs)
	  	following = UserProfile.objects.is_following(self.request.user, self.get_object())
	  	context['following'] = following
	  	context['recommended'] = UserProfile.objects.recommended(self.request.user)
	  	return context


class UserFollowView(View):
 	def get(self, request, username, *args, **kwargs):
 		toggle_user = get_object_or_404(User, username__iexact=username)
 		if request.user.is_authenticated():
 			is_following = UserProfile.objects.toggle_follow(request.user, toggle_user)
 		return redirect("profiles:detail", username=username)
 		# user_profile, created = UserProfile.objects.get_or_create(user=request.user)
 			# if toggle_user in user_profile.following.all():
 			# 	user_profile.following.remove(toggle_user)
 			# else:
 			# 	user_profile.following.add(toggle_user)

class EditProfileView(UserChangeForm):

	class Meta:
		model = User
		fields = (
			'username',
			'first_name',
			'last_name',
			'email',
			'password',
			)

accounts/templates/accounts/change_password.html
{% extends "base.html" %}
{% block script %}
<script>
    $(document).ready(function(){
    
        $("#id_email").css("width", "50%");
        $(".errorlist").css("color", "red");

      $("#id_old_password").attr('placeholder', 'Old password');
      $("#id_new_password1").attr('placeholder', 'New password');
      $("#id_new_password2").attr('placeholder', 'Confirm password');
        });
</script>
{% endblock %}
{% block head %}
<style>
  body{
    background-color: #ebebeb;
  }

 
</style>
<title>Change Password</title>
<link rel="stylesheet" href="https://abs.twimg.com/a/1515531216/css/t1/twitter_core.bundle.css" class="coreCSSBundles">
    <link rel="stylesheet" class="moreCSSBundles" href="https://abs.twimg.com/a/1515531216/css/t1/twitter_more_1.bundle.css">
    <link rel="stylesheet" class="moreCSSBundles" href="https://abs.twimg.com/a/1515531216/css/t1/twitter_more_2.bundle.css">

    <link rel="dns-prefetch" href="https://pbs.twimg.com">
    <link rel="dns-prefetch" href="https://t.co">
    <link rel="preload" href="https://abs.twimg.com/k/en-gb/init.en-gb.0aa8dbebc3cfc543c67e.js" as="script">
    <link rel="preload" href="https://abs.twimg.com/k/en-gb/0.commons.en-gb.cf50ad922f8e5cf8b01f.js" as="script">

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
{% endblock %}

{% block content%}
  <div id="doc"  class="route-login login-responsive">

        <div id="page-outer">
          <div id="page-container" class="AppContent wrapper wrapper-login">

            <div class="page-canvas">

  <div class="signin-wrapper" data-login-message="" style="font-family:lato; font-style: normal;">
    <h1 class="login" style="font-family:lato; font-style: normal; font-weight: bold">Change Password</h1>
    {% if form.errors %}
      {% if form.old_password.errors %}
        <p> {{ form.old_password.errors }} </p>
      {% endif %}

      {% if form.new_password1.errors %}
        <p>{{ form.new_password1.errors }} </p>
      {% endif %}


      {% if form.new_password2.errors %}
        <p>{{  form.new_password2.errors }}</p>
      {% endif %}

    {% endif %}
 <form method="post" class="t1-form clearfix signin js-signin" > 



  
      <fieldset>

  <legend class="visuallyhidden">Change Password</legend>


    {% csrf_token %}
      <!--   {{form.as_p }} -->
    <div class="clearfix field">
     
         {{ form.old_password  }}
    </div>
     <div class="clearfix field">
     
         {{ form.new_password1 }}
    </div>
    <div class="clearfix field">
     
         {{ form.new_password2  }}
    </div>
 



</fieldset>

      <div class="captcha js-captcha">
      </div>
      <div class="clearfix">


  <button type="submit" class="submit EdgeButton EdgeButton--primary EdgeButtom--medium">Change</button>

  <div class="subchck">
 <!--    <label class="t1-label remember">
      <input type="checkbox" value="1" name="remember_me" checked="checked">
      Remember me
      <span class="separator">·</span>

    </label> -->
  </div>
</div>

    </form>
  </div>

  <div class="clearfix mobile has-sms">
    
    <p class="signup-helper">
    
      <a id="login-signup-link" href="/">Return to home&#32;&raquo;</a>
    </p>

  </div>

</div>

          </div>
        </div>
</div>
{% endblock content %}


<!-- <form method="POST">
   {% csrf_token %}
   {{form.as_p }}
   <button type="submit">Update</button>
</form> -->

accounts/templates/accounts/edit_profile.html
{% extends "base.html" %}
{% block script %}
<script>
    $(document).ready(function(){
    
      $("#id_email").css("width", "50%");
        });

      $("#id_username").attr('placeholder', 'User name');
      $("#id_first_name").attr('placeholder', 'First name');
      $("#id_last_name").attr('placeholder', 'Last name');
      $("#id_email").attr('placeholder', 'Email');
</script>
{% endblock %}
{% block head %}
<style>
  body{
    background-color: #ebebeb;
  }
   input, textarea,
  {
    width: 50% !important;
  }
 .textclass
  {
    width: 50% !important;
  }
</style>
<title> Edit Profile</title>
<link rel="stylesheet" href="https://abs.twimg.com/a/1515531216/css/t1/twitter_core.bundle.css" class="coreCSSBundles">
    <link rel="stylesheet" class="moreCSSBundles" href="https://abs.twimg.com/a/1515531216/css/t1/twitter_more_1.bundle.css">
    <link rel="stylesheet" class="moreCSSBundles" href="https://abs.twimg.com/a/1515531216/css/t1/twitter_more_2.bundle.css">

    <link rel="dns-prefetch" href="https://pbs.twimg.com">
    <link rel="dns-prefetch" href="https://t.co">
    <link rel="preload" href="https://abs.twimg.com/k/en-gb/init.en-gb.0aa8dbebc3cfc543c67e.js" as="script">
    <link rel="preload" href="https://abs.twimg.com/k/en-gb/0.commons.en-gb.cf50ad922f8e5cf8b01f.js" as="script">

    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
{% endblock %}

{% block content%}
  <div id="doc"  class="route-login login-responsive">

        <div id="page-outer">
          <div id="page-container" class="AppContent wrapper wrapper-login">

            <div class="page-canvas">

  <div class="signin-wrapper" data-login-message="" style="font-family:lato; font-style: normal;">
    <h1 class="login" style="font-family:lato; font-style: normal; font-weight: bold">Edit Profile</h1>
  <!--   {% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>

    {% endif %}
{% endif %} -->
 <form method="post" class="t1-form clearfix signin js-signin" > 



  
      <fieldset>

  <legend class="visuallyhidden">Edit Profile</legend>

    <!-- {{form.as_p }} -->
    {% csrf_token %}
    <div class="clearfix field">
     
         {{ form.first_name  }}
    </div>
     <div class="clearfix field">
     
         {{ form.last_name  }}
    </div>
    <div class="clearfix field">
     
         {{ form.username  }}
    </div>
    <div class="clearfix field ">
   <p class="email">
        {{ form.email  }}
      </p>
    </div>



</fieldset>

      <div class="captcha js-captcha">
      </div>
      <div class="clearfix">


  <button type="submit" class="submit EdgeButton EdgeButton--primary EdgeButtom--medium">Update</button>

  <div class="subchck">
 <!--    <label class="t1-label remember">
      <input type="checkbox" value="1" name="remember_me" checked="checked">
      Remember me
      <span class="separator">·</span>

    </label> -->
  </div>
</div>

    </form>
  </div>

  <div class="clearfix mobile has-sms">
    <p class="signup-helper">
    
      <a id="login-signup-link" href="/profile/password/">Change Password&#32;&raquo;</a>
    </p>
    <p class="signup-helper">
    
      <a id="login-signup-link" href="/">Return to home&#32;&raquo;</a>
    </p>

  </div>

</div>

          </div>
        </div>
</div>
{% endblock content %}
<!-- <form method="POST">
   {% csrf_token %}
   {{form.as_p }}
   <button type="submit">Update</button>
</form> -->

accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% block script %}
		<script>
			$(document).ready(function(){
			loadTweetContainer("tweet-container")
		  });
        </script>

{% endblock script %}

{% block content %}
<div class="SearchNavigation">
	<div class="SearchNavigation-canopy u-bgUserColor">
		<div class="SearchNavigation-textContainer">
			<h1 class="SearchNavigation-titleText" style="padding-left: 3em;" dir="ltr">
				<h1 class="ProfileHeaderCard-name" style="margin-left:5em;margin-top: 5px box-shadow:1px 1.5px 1px 1.5px #888888">{{ object.username }} {{ object.email }} {{ object.first_name}} {{ object.last_name}}</h1>

			</h1>
		</div>

	</div>
	<div class="AdaptiveFiltersBar" style="height:3em">
		<div style="">
					<a style="margin-left:12em">
						<p class="ProfileHeaderCard-screenname u-inlineBlock u-dir" style="margin-top: 15px"> Followers: {{object.followed_by.all.count}}
						</p>
					</a>

					<div class="u-floatRight u-textRight with-rightCaret" style="margin-right: 10em;margin-top: 10px;">
						<a class='btn btn-link' style="text-decoration-color:white; border: 1px solid #1da1f2;border-radius: 25px; color: black; background-color: #1da1f2;width:auto;padding:5px" href='{{ object.profile.get_follow_url }}'>
							{% if following %}Unfollowing{% else %}Follow{% endif %}
						</a>
					</div>
			</div>
	</div>
</div>
<div id="page-outer" style="margin-top:8em">
	<div id="page-container" class="AppContent wrapper wrapper-home">

		<div class='Grid Grid--withGutter' style="margin-top:15em">
				<div class='Grid-cell u-size1of3 u-lg-size1of4' style="background-color: white; height: 400px; border-radius:15px; box-shadow: 1px 1.5px 1px 1.5px #888888">
					<div class="Grid Grid--withGutter">
						<div class="Grid-cell" style="margin:5px">
							<div class="ProfileSidebar ProfileSidebar--withLeftAlignment">
								<h1 class="ProfileHeaderCard-name" style="background-color: #1c94e0;padding:1em;border-radius:15px;" > Following : <large style="color:white">{{ object.profile.get_following.count}}</large></h1>
								   	<!--  {{ object.profile.following}} -->
								{% for user in object.profile.get_following %}
								  <a style="margin: 5px; color: black;padding:5px;display: inline-block;text-align: center;"  href='/{{ user.username}}'>{{ user.username }}</a><br/>
								  {% empty %}
								  <h4 class="ProfileHeaderCard-screenname u-inlineBlock u-dir" style="margin-top: -10px"> Not following  users </h4>
								    {% endfor %}
								  <h1 class="ProfileHeaderCard-name"  style="background-color: #1c94e0;padding:1em;margin-top: 10px;border-radius:15px;">Followed By</h1>
								   <!--  {{ object.profile.following}} -->
									{% for profile in object.followed_by.all %}
								 <a style="margin: 5px; color: black;padding:5px;display: inline-block;text-align: center;"  href='/{{ profile.user.username}}'>{{ profile.user.username }}</a>
								  <br/>
								  {% empty %}
								  <h4 class="ProfileHeaderCard-screenname u-inlineBlock u-dir"> Not followed by  any users </h4>
								    {% endfor %}

							</div>
						</div>
					</div> 		  
				</div>
				<div class='Grid-cell u-size2of3 u-lg-size3of4' style="padding-left: 25px; width: 80%;">
					<div class="Grid Grid--withGutter" style="width:100%">

						<div class="Grid-cell u-size2of3 u-lg-size3of4" style="background-color: white; width:80% !important;border-radius:15px; box-shadow: 1px 1.5px 1px 1.5px #888888">
							<h1 class="ProfileHeaderCard-name" style="background-color: #1c94e0;padding:1em;text-align:center"  >Tweets</h1>
							<div id='tweet-container' style="padding:2em" data-url='/api/{{ object.username }}/tweet'>
							</div>
							<a style="text-align:center;padding:10em" href='#' id='loadmore'>Load More Tweets</a>
						</div>


					</div>
				</div>
		</div>
	</div>
</div>

 {% endblock content %}